---
title: "Demo Stylish Article"
# Output formats
format:
  stylisharticle-html:
    # Color example, see "Text color"
    css: colors.css
  docx:
    toc: true
  stylisharticle-pdf:
    keep-tex: true
    # Color example, see "Text color"
    header-includes:
      \definecolor{grey}{RGB}{191, 191, 191}
# Authors (https://quarto.org/docs/journals/authors.html#author-schema)
author:
  - name: Félix Romiguière
    affiliations:
      - name: Université de Montpellier
        department: Scientific Department
        address: Somewhere
        city: Montpellier
        country: France
        postal-code: 9999
    orcid: 0000-0000-0000-0000
    email: felix.romiguiere@etu.umontpellier.fr
    url: https://example.org/
# Abstract and Keywords
abstract: |
  Document pour le début de rédaction de l'article sur Tahiti Soundscape
keywords: [template, demo]
# Bibliography
reference-section-title: References
bibliography: references.bib
# Language
lang: fr-FR
otherlangs: en-GB
# Code options 
# https://quarto.org/docs/computations/execution-options.html
execute:
  # show code chunk output
  include: true
  # Show the code in the output
  echo: false
  # Show messages
  message: false
  # Show warnings
  warning: false
  # Cache code results
  cache: true
# Template specific
journalinfo: "Publication reference"
archive: "DOI: xxx/xx"
keywordlabel: Keywords
corrauthorlabel: Corresponding Author
---

# Introduction

*Oceanic island urbanisation and non -native species invasion*

Oceanic island are small sized with unique biodiversity and simplified communities shaped by human influence.
They so stands out as unique ecosystems useful to study the impacts of human activities [@whittaker2017; @russell2019].
Oceanic island tends to be more sensitive to species introductions and extensive anthropogenic land-used modification [@whittaker2017; @spatz2017; @russell2019].
For island in particular, avian species have been among the most concerned taxa, having their community assemblages shaped by both invasion and extensive urbanisation processes [@boyer2014; @spatz2017; @rogers2021].

*Interspecific competition and homogenization in islands*

Non-native birds are issued from specific families (e.g., Galliniformes,Columbidae, Fringillidae, Passeridae, Estrildidae and Sturnidae ..) mainly introduced for hunting and aesthetic purposes [@blackburn2001; @dyer2017].
These species show peculiar traits adapted to urban and agricultural landscapes, whereas native birds from oceanic island tends to mostly include species occuring in forests [@soares2021].
Non-native species may outcompete native for essential ressources, and can affect population dynamic for native species [@davis2003].
As shown with the introduction of the Japanese white eye in Hawai'i [@blackburn2009].
Interspecific competition can stand as a strong driver for native non-native species assemblages [@mcgill2006].
Combined effect of the growing loss of native ecosystems and continued introduction of birds species, especially of forest-dwelling birds, intensify non-native competition threats [@sax2007].
Moreover, the introduction of functionnaly similar species, promotes negative impact through functionnal homogenisation of island bird assemblages [@sobral2016; @sayol2021; @soares2022].

*General context of Soundscape and ecoacoustic, acoustic indices*

Advance in soundscape ecology, enabled better understanding of structure and dynamic of the sonic environments [@pijanowski2011].
The soundscape incorpore all components, classified according to the sound sources: geophony (climate and geography), biophony (all living organisms), and anthrophony (human activities) [@pijanowski2011].
Complexity of these acoustic emissions can be characterise via acoustic indices that creates a numeric summary of the soundscape [@farina2012].
Ecological meaning is inferred by relating acoustic indices to diversity metrics [@towsey2014; @eldridge2018; @dröge2021], habitat conditions [@fuller2015; @sánchez-giraldo2021; @rudge2026] or temporal dynamics [@gage2014].
They can also provide indicators on soundscape disturbances [@villanueva-rivera2011].

*Implication for oceanic islands*

In oceanic islands, ecological complexity is threathened by human pressure (urbanisation, invasion).
Soundscape studies offers a good tool to monitor invasions, extinction, and assemblage turnover [@farina2012; @ribeiro2022].
Such example exist with the study of an invasive ant leading to impoverishment of the soundscape in New Caledonian forests [@gasc2018].
Species assemblages interact acoustically and reflect a dynamic processes called an acoustic community [@lellouch2014; @farina2016].
In oceanic islands, acoustic communities are modified by non-native species introduction, having strong implications for native species acoutic habitat and their soundtope quality modification [@farina2014; @merchant2015].
The soundtope represent the acoustic pattern created by the distribution of biophonies [@farina2014].
Whereas the acoustic habitat incorpore the soundtope and add the environmental acoustic conditions in which the species assemblage is leaving [@merchant2015; @farina2016].

*Acoustic implication*

Recent studies have pointed out the potential importance of invasive species as underappreciated source of novel noise, that could alter acoustic communication among native species [@hopkins2022] [@hunt2024].
In the context of oceanic island, diminished bird richness reflect fewer vocalizing species, resulting in less saturated soundscapes than mainland [@robert2019].
So, acoustic interferences are anticipated to lessened on islands.
Yet, introduction of non-native species are numerous and is expected to continue to increase in islands [@seebens2017].
Compared to native species, loudness and high occurrence rate of vocalization can be characteristic for invasive species [@hopkins2022].
For example, over the course of one year, invasive Pekin Robins’ (*Leiothrix lutea*) calls made up 37% of all bird songs in a shrubland in their invaded range in Europe [@farina2013].
Likewise, calls of invasive birds such as Common Mynas (*Acridotheres tristis*) seem to dominate the urban environments they have invaded (personal information from [@hopkins2022]).
Plus, timing of calls between native and invasive are very similar, and may creates overlap, important for acoustic competition [@farina2013; @bleach2015a]

This novel biotic noises are quite attuned to mask vital information encoded in acoustic signals, and may impact frequencies, reduce perception and discrimination of the latter [@lohr2003].
This masking effect can negatively affect communication, movement, vigilance, mating and foraging [@shannon2016].
Affecting individual survival and reproductive success [@halfwerk2011; @medeiros2017].
Therefore, the calls of non-native species, can bring a significant avenue for acoustic competition with native species and may dominates insular soundscape which favored it's homogenization [@farina2013].
Still, evidence in oceanic island are scarce and need further investigation [@hopkins2022; @hunt2024].

*Problematisation*

Here, we sought to investigate the variation in saturation, intensity, complexity of signal emissions at the acoustic habitat and soundtope level of the soundscape, in relation to native/non-native bird assemblage and habitat factors, across the habitat gradients Tahiti.
We predicted that urbanisation gradients drives relevant acoustic indices results for the acoustic habitat level [@fairbrass2017].
We also predicted that differences in bird assemblage would drive the variation at the soundtope level, and that non-native species in these assemblages have higher implication in acoustic indices computation compared to native species.
Given that urbanisation gradient and non-native dominated assemblage represents a combined effect.
We expect that urban sites have more saturated and complex soundscape patterns due to both factors compared to deep forested sites.

# Methods

*Study area*

The study was conducted in Tahiti, French Polynesia.
Tahiti is the largest (1,042 km²) island of French Polynesia [@monnet1993].
The climate is tropical with an average annual temperature of 26,5 °C and annual rainfall of 1700 mm in the coastal plain of the leeward coast of Tahiti Nui, reaching 4000 mm on the windward coast and Tahiti Iti, and up to 8000 mm in the center of Tahiti Nui (Laurent source quoin atlas meteorologique accès?).
Islands of the Pacific ocean undergoes strong impoverishment with numerous bird extinctions due to first Polynesian arrival in the 13th century and Europeans in the 18th century (Thibault 1988).[@bellwood1978; @monnet1993; @steadman1995] From 1960 to 1990, strong habitat modification took places due to development, costal urbanisation and forest clearance (Blanchet 1986)[@monnet1993].
In Tahiti "..." terrestrials bird species occurs, 12 of them are non-native [@thibault2017].
Introduced birds have generally the highest densities in lowland, non-forested habitats such as urban areas or agricultural fields, and lower densities in high-elevation, contiguous forest, where native birds resides [@monnet1993] (besoin source moins loin pour Tahiti or personal observation).

*Acoustic data collection*

Passive acoustic data was collected using SongMeter SM2 and SM4 digital recording devices (Wildlife Acoustics, Maynard, MA, USA) from 2024 to 2026.
In total 69 sites from different habitat types ( Forest = , ... rural or suburban = , .. Urban = ) were surveyed in valleys along an attitudinal gradients.
Stations recorded along the same valley's gradient, so each gradient as staggering dates.
Acoustic recording units (ARUs) were programmed to record continuously and placed at 1,5 meters above the ground.Devices recorded for "..." per station, with a total of "..." hours recorded.
Recordings were made as .WAV files with a "..." Hz sampling rate and gain of "..." dB, with monophonic and 16 Bits formats.

*Soundscape index metrics*

We selected nine relevant acoustic indices to encompass the sonic emissions heterogeneity for the acoustic habitat and the soundtope of each sampling site.
Choice of indices were based on their relevance to reflect patterns of variability, heterogeneity, complexity of both soundscape level.
The use of several acoustic indices was prioritize as multi index analysis have been shown to be more effective than single index investigations [@bradfer-lawrence2020].
Acoustic indices were estimated for each 10-min recordings.
We used indices median output per hour for better control of index variation [@bradfer-lawrence2019].
Acoustic indices output were normalized to facilitate comparisons.

Two different frequency limits were applied for the upper limit and a low frequency threshold for devices glitches.
For the soundtope the limit was (... Hz) to reflect Tahiti bird community emissions.
Recordings containing rainfall sounds were excluded from the calculation at this soundscape level.
For the acoustic habitat, the limit was (... Hz) to encompass all sonic emissions that could affect the bird assemblages.
Recording containing rainfall sounds were included in the calculation at this soundscape level.
All indices were estimated using the default settings with the packages ‘soundecology’ (...) and seewave (...) packages in R (..).

(Table used for soundscape and bird acoustic community monitoring, with hypothesis)

*Habitat metrics*

Two metrics, the Hard Surface Area (HSA) and the open herbaceous cover (HERB) were chosen to reflect habitat types and heterogeneity along the attitudinal gradients.
HSA and HERB ranges between 0 and 100 %.
Respectively, higher values indicates the important cover of human-modified surfaces and open herbaceous areas.
Habitat covers map was estimated using polygon surfaces in 100 meter radius circle around each ARUs positions in Google Earth (Google Earth Pro.7.3.7.1327).

*Avian caracterisation*

Two ten minute aural and visual identification in acoustic recordings was conducted for each site, to obtain bird richness count.
Aural and visual acoustic identification were conducted from 06:00 am to 06:10 am in recordings free of rainfall or strong acoustic disturbance.
From the aural identification database, several assemblage metrics were derived: total richness (count), non-native richness (count), presence of native bird (binomial), presence of Myna (binomial).
Non-native bird species encountered were "..." Native bird species monitored were "...".

*Bird assemblage metrics in response to habitat characteristic analysis*

Habitat as direct driver of bird assemblage was investigated.
The three bird assemblage metrics were modeled independently as responses variables using "..." for or "..." for "..." distributions using the habitat metrics and altitude as independent fixed variables.
All generalized linear mixed-effects models (GLMER) were made using the "GlmmTMB" package [@brooks2017].

*Acoustic indices in response to bird assemblage and habitat metrics analysis*

Prior to analysis, acoustic indices output were tested for correlations.

To investigate if acoustic indices reflect metrics of native/non native bird assemblage, GLMER were used to model each acoustic index (...) individually as response variable, for both acoustic habitat and soundtope level.
In response to the following independent variables: one assemblage metric at a time and habitat metrics.
All models included a control fixed effect for the time (hour of the day) to account for temporal autocorrelation and random fixed effects for the site and commune.
Models used a "..." distribution with a "..." function.
All statistical analyses were performed in R v.().
