---
title: "Mat_Met"
format: 
  docx:
    toc: true
  html:
    css: colors.css
editor: visual
bibliography: references.bib
execute:
  # show code chunk output
  include: true
  # Show the code in the output
  echo: false
  # Show messages
  message: false
  # Show warnings
  warning: false
  # Cache code results
  cache: true
---

*Study area*

- The study was conducted in Tahiti, French Polynesia.
  An island of the Pacific ocean, that undergoed strong impoverishment with numerous bird extinctions due to 1st Polynesian arrival (13th) and Europeans in the 18th century (Thibault 1988).[@bellwood1978; \@monnet1993; @steadman1995]

- From 1960 to 1990, strong habitat modification took places due to development, costal urbanisation and forest clearance (Blanchet 1986).
  [@monnet1993]

-  Tahiti is the largest (1,042 km²) island of French Polynesia [@monnet1993].
  The climate is tropical with an average annual temperature of 26,5 °C and annual rainfall of 1700 mm in the coastal plain of the leeward coast of Tahiti Nui, reaching 4000 mm on the windward coast and Tahiti Iti, and up to 8000 mm in the center of Tahiti Nui (Laurent source quoin atlas meteorologique accès?)

- Introduced number of bird species exceed native species left in Tahiti, out of the total .....
  terrestrials bird species, 12 of them are non-native [@thibault2017].
  Introduced birds have generally the highest densities in lowland, non-forested habitats such as urban areas or agricultural fields, and lower densities in high-elevation, contiguous forest, where native birds resides [@monnet1993].

*Acoustic data collection*

- Passive acoustic data was collected using SongMeter SM2 and SM4 digital recording devices (Wildlife Acoustics, Maynard, MA, USA) from 2024 to 2026.
  In total 69 sites from different habitat types ( Forest = , ... rural subrubani = , .. Urban = ) were surveyed along valleys altitudinal gradients.

- Due to the limited number of ARUs, stations recorded for a week for a same valley, then changes at another attitudinal gradient, thus each gradient as staggering dates.

- Acoustic recording units (ARUs) were programmed to record continuously and placed at 1,5 meters above the ground.
  All devices recorded for ...
  per station, with a total of ...
  hours

- Recordings were made as .WAV files with a ....
  Hz sampling rate and gain of ...
  dB, with monophonic and16 Bits.

Besoin d'un figure carte avec nos sites et le rayon quon considère autour de nos sites...
avces au moins la composition urbaine, forestière et suburbain en schéma grotesque.

*Soundscape index metrics*

- We selected nine relevant acoustic indices to englobe the acoustic heterogeneity of the acoustic habitat and the soundtope in each sampling site.
  (figg)

- Acomplexity indices...?

- The use of several acoustic indices was prioritize as multi index analysis have been shown to be more effective than single index investigations [@bradfer-lawrence2020]

- Acoustic indices were estimated for each 10-min recordings.
  We used indices median output per hour for better control of index variability [@bradfer-lawrence2019].
  Acoustic indices output were normalized to facilitate comparisons.

- Two differents frequency limits were applied for the upper limit, while a law frequency threshold for devices glitches was considered.

- For the soundtope the limit was (... Hz) to focus in biophonic component, as bird community in Tahiti is concentrated below this threshold.
  Recordings containing rainfall sounds were excluded from the calculation at this soundscape level.

- For the acoustic habitat, the limit was (... Hz) to englobe all sonic emissions that could affect the bird assemblages (... - ... Hz).
  Recording containing rainfall sounds were included in the calculation at this soundscape level.

- All indices were estimated using the default settings with the packages ‘soundecology’ (...) and seewave (...) packages in R (..).

(Table used for soundscape and bird acoustic community monitoring, with hypothesis

*Habitat metrics*

- Two different metrics, the Hard Surface Area (HSA) and the open herbaceous cover (HERB) were chosen to reflect habitat types and heterogeneity along the attitudinal gradients
- HSA and HERB ranges between 0 to 100. Higher values indicates the important cover of hard surfaces and open herbaceous areas respectively. Habitat covers map was estimated using polygon surfaces in 100 meter radius circle around each ARUs positions in Google Earth (Google Earth Pro. 7.3.7.1327).

*Avian caracterisation*

- For each site, two ten minute aural and visual identification in acoustic recordings was conducted to obtain bird richness count.
  Aural and visual acoustic identification were conducted from 06:00 am to 06:10 am for two successive days, without rainfall or strong acoustic disturbance.

- From the aural identification dataset, several assemblage metrics were derived.

- Non-native bird species encountered were...

- Native bird species monitored corresponded to...

*Data analysis*

- All statistical analyses were performed in R v.().
  To investigate acoustic indices relationships with bird assemblage and habitat metrics, we used generalized linear mixed-effects models (GLMER).

- A correlation analysis was ran to evaluate associations between acoustic indices, possibly redundant indices were excluded.

?Nevertheless, the testSpatialAutocorrelation function in DHARMa was used to test model residuals for spatial autocorrelation

*Bird assemblage metrics in response to habitat characteristic*

Habitat as direct driver of bird assemblage was investigated in GLMER ( ).
The three bird assemblage metrics were modelled independently as responses variables using ...
or ...
distributions using the habitat metrics and altitudes as independent fixed variables.
All GLMER were made using the "..."package ([@brooks2017]).

*Acoustic indices in response to bird assemblage and habitat metrics*

Prior to modelisation, acoustic indices output were tested for correlations

To investigate if acoustic indices reflect metrics of native/non native bird assemblage, GLMER were used to model each acoustic index ( ) individually, for both soundscape level.
That in response to the following independent variables: one assemblage metric at a time and habitat metrics.

All models included a control fixed effect for the time (hour of the day) to account for temporal autocorrelation and ranfom fixed effects for the site and commune.

All models used a ...
distribution with a ...
function.

- Each acoustic index was modelled individually as response variable with one bird assemblage metric, the hard surface area and open herbaceaous cover as independant fixed effect. Site and commune considered as random effects. Models included the control fixed effect for the time (hour of the day) to account for temporal autocorrelation.

Ca serait cool de pouvoir tester à quel altitude on commence à avoir un switch dans les valeurs montrant qu'on passe a un autre soundtope?
ou qu'on est donc sur un soundtone.
